### ISSUE TITLE
hvnc builde

### ISSUE THREAD

**Issue by chief514** [Tlgyt/The-Collection#1]
the builder in the hvnc is not working

**Comment by glebkhil** [comment]
how did you fix the problem?

**Comment by 0x9ef** [comment]
ye, i think in builder hardcoded Lotus v6 hash and builder verify this hash from hask.idkey and u cannot select another VPS server ip:port, try to dissasembl today :)

**Comment by glebkhil** [comment]
There when creating a build, the builder climbs on some Amazon servers
