### ISSUE TITLE
DONT SHOW RATS.

### ISSUE THREAD

**Issue by scripter-cell** [Tlgyt/The-Collection#7]
I downloaded it bechause i needed "rats" buth when i open any rat there is no client (everything else is ok) just no client

**Comment by yatt-ze** [comment]
Hey that's cool man.
Not anything I can do about though, maybe do some research on how this all works first.

And probably not the best idea to use any of this to break the law, or broadcast your intent too, this is only my collection of shit I had as research material

**Comment by scripter-cell** [comment]
HELLO!-- Thanks for your reply!
I just wanted to decompile them bechause i needed source codes :)


P.S. I didnt want to infect anyone, im just making (idk how to call it, so i say  "antirat") that will detect crypted rats, and show all info about pc thats connected, and break connection from client, and i needed to use diffrent crypt methods qnd rats. 

Thanks again, sorry for wasting your time.
